recipe: default.v1

language: de

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper

policies:
- name: RulePolicy
- name: MemoizationPolicy
- name: TEDPolicy
  epochs: 100
assistant_id: 20260408-080458-obnoxious-screw
